//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnroladorAccesoDatos.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cadena
    {
        public long IdCadena { get; set; }
        public string GuidCadena { get; set; }
        public string NombreCadena { get; set; }
        public Nullable<long> Sincronizado { get; set; }
    }
}
