//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnroladorAccesoDatos.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        public long IdContrato { get; set; }
        public string GuidContrato { get; set; }
        public string GuidEmpresa { get; set; }
        public string GuidCuenta { get; set; }
        public string GuidCargo { get; set; }
        public string GuidEmpleado { get; set; }
        public string InicioVigencia { get; set; }
        public string FinVigencia { get; set; }
        public string CodigoContrato { get; set; }
        public Nullable<long> ConsideraAsistencia { get; set; }
        public Nullable<long> ConsideraCasino { get; set; }
        public Nullable<long> Sincronizado { get; set; }
    }
}
