//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnroladorAccesoDatos.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public long IdCuenta { get; set; }
        public string GuidCuenta { get; set; }
        public string GuidEmpresa { get; set; }
        public string NombreCuenta { get; set; }
        public string FechaUltimoCierre { get; set; }
        public Nullable<long> Sincronizado { get; set; }
    }
}
