//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnroladorAccesoDatos.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispositivo
    {
        public long IdDispositivo { get; set; }
        public string GuidDispositivo { get; set; }
        public string GuidInstalacion { get; set; }
        public string NombreDispositivo { get; set; }
        public string Host { get; set; }
        public Nullable<long> Puerto { get; set; }
        public Nullable<long> Tipo { get; set; }
        public Nullable<long> Sincronizado { get; set; }
    }
}
