//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnroladorAccesoDatos.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Huella
    {
        public long IdHuella { get; set; }
        public string GuidHuella { get; set; }
        public string GuidEmpleado { get; set; }
        public string Data { get; set; }
        public Nullable<long> Tipo { get; set; }
        public Nullable<long> Sincronizado { get; set; }
    }
}
