//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnroladorAccesoDatos.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class PorSincronizar
    {
        public long IdPorSincronizar { get; set; }
        public string IdRegistroASincronizar { get; set; }
        public string TablaASincronizar { get; set; }
        public string FechaCambio { get; set; }
        public Nullable<long> TipoModificacion { get; set; }
    }
}
