//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnroladorAccesoDatos.SQLite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SQLiteEnrollEntities : DbContext
    {
        public SQLiteEnrollEntities()
            : base("name=SQLiteEnrollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cadena> Cadena { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<EmpleadoTurnoServicioCasino> EmpleadoTurnoServicioCasino { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Hardware> Hardware { get; set; }
        public virtual DbSet<Instalacion> Instalacion { get; set; }
        public virtual DbSet<PorSincronizar> PorSincronizar { get; set; }
        public virtual DbSet<Sincronizacion> Sincronizacion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<EmpleadoDispositivo> EmpleadoDispositivo { get; set; }
        public virtual DbSet<Dispositivo> Dispositivo { get; set; }
        public virtual DbSet<Huella> Huella { get; set; }
        public virtual DbSet<ServicioCasino> ServicioCasino { get; set; }
        public virtual DbSet<TurnoServicio> TurnoServicio { get; set; }
    }
}
