//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnroladorAccesoDatos.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurnoServicio
    {
        public long IdTurnoServicio { get; set; }
        public string GuidTurnoServicio { get; set; }
        public string GuidServicio { get; set; }
        public string NombreTurnoServicio { get; set; }
        public Nullable<long> Vigente { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFin { get; set; }
        public Nullable<long> Sincronizado { get; set; }
    }
}
