//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnroladorStandAloneV2.EnroladorServicioWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EnroladorServicioWeb.IEnroladorServicioWeb")]
    public interface IEnroladorServicioWeb {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/IdentificarHardware", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/IdentificarHardwareResponse")]
        bool IdentificarHardware(System.Guid hardwareId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/IdentificarHardware", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/IdentificarHardwareResponse")]
        System.Threading.Tasks.Task<bool> IdentificarHardwareAsync(System.Guid hardwareId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/AutenticacionUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/AutenticacionUsuarioResponse")]
        EnroladorAccesoDatos.Dominio.POCOUsuario AutenticacionUsuario(string nombreUsuario, string claveUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/AutenticacionUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/AutenticacionUsuarioResponse")]
        System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOUsuario> AutenticacionUsuarioAsync(string nombreUsuario, string claveUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/Revalidar", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/RevalidarResponse")]
        EnroladorAccesoDatos.Dominio.POCOUsuario Revalidar(EnroladorAccesoDatos.Dominio.POCOUsuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/Revalidar", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/RevalidarResponse")]
        System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOUsuario> RevalidarAsync(EnroladorAccesoDatos.Dominio.POCOUsuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeHuellasDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeHuellasDelUsuarioResponse")]
        EnroladorAccesoDatos.Dominio.POCOHuella[] LeeHuellasDelUsuario(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeHuellasDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeHuellasDelUsuarioResponse")]
        System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOHuella[]> LeeHuellasDelUsuarioAsync(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeCadenasDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeCadenasDelUsuarioResponse")]
        EnroladorAccesoDatos.Dominio.POCOCadena[] LeeCadenasDelUsuario(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeCadenasDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeCadenasDelUsuarioResponse")]
        System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOCadena[]> LeeCadenasDelUsuarioAsync(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeCargosDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeCargosDelUsuarioResponse")]
        EnroladorAccesoDatos.Dominio.POCOCargo[] LeeCargosDelUsuario(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeCargosDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeCargosDelUsuarioResponse")]
        System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOCargo[]> LeeCargosDelUsuarioAsync(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeContratosDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeContratosDelUsuarioResponse")]
        EnroladorAccesoDatos.Dominio.POCOContrato[] LeeContratosDelUsuario(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeContratosDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeContratosDelUsuarioResponse")]
        System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOContrato[]> LeeContratosDelUsuarioAsync(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeCuentasDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeCuentasDelUsuarioResponse")]
        EnroladorAccesoDatos.Dominio.POCOCuenta[] LeeCuentasDelUsuario(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeCuentasDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeCuentasDelUsuarioResponse")]
        System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOCuenta[]> LeeCuentasDelUsuarioAsync(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeDispositivoDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeDispositivoDelUsuarioResponse")]
        EnroladorAccesoDatos.Dominio.POCODispositivo[] LeeDispositivoDelUsuario(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeDispositivoDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeDispositivoDelUsuarioResponse")]
        System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCODispositivo[]> LeeDispositivoDelUsuarioAsync(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeEmpleadosDispositivos", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeEmpleadosDispositivosResponse")]
        EnroladorAccesoDatos.Dominio.POCOEmpleadoDispositivo[] LeeEmpleadosDispositivos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeEmpleadosDispositivos", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeEmpleadosDispositivosResponse")]
        System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOEmpleadoDispositivo[]> LeeEmpleadosDispositivosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeEmpresaDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeEmpresaDelUsuarioResponse")]
        EnroladorAccesoDatos.Dominio.POCOEmpresa[] LeeEmpresaDelUsuario(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeEmpresaDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeEmpresaDelUsuarioResponse")]
        System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOEmpresa[]> LeeEmpresaDelUsuarioAsync(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeTodasHuellas", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeTodasHuellasResponse")]
        EnroladorAccesoDatos.Dominio.POCOHuella[] LeeTodasHuellas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeTodasHuellas", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeTodasHuellasResponse")]
        System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOHuella[]> LeeTodasHuellasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeInstalacionesDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeInstalacionesDelUsuarioResponse")]
        EnroladorAccesoDatos.Dominio.POCOInstalacion[] LeeInstalacionesDelUsuario(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeInstalacionesDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeInstalacionesDelUsuarioResponse")]
        System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOInstalacion[]> LeeInstalacionesDelUsuarioAsync(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeTodosEmpleados", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeTodosEmpleadosResponse")]
        EnroladorAccesoDatos.Dominio.POCOEmpleado[] LeeTodosEmpleados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeTodosEmpleados", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeTodosEmpleadosResponse")]
        System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOEmpleado[]> LeeTodosEmpleadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeServicioCasinoDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeServicioCasinoDelUsuarioResponse")]
        EnroladorAccesoDatos.Dominio.POCOServicioCasino[] LeeServicioCasinoDelUsuario(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeServicioCasinoDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeServicioCasinoDelUsuarioResponse")]
        System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOServicioCasino[]> LeeServicioCasinoDelUsuarioAsync(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeTurnoServicioDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeTurnoServicioDelUsuarioResponse")]
        EnroladorAccesoDatos.Dominio.POCOTurnoServicio[] LeeTurnoServicioDelUsuario(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeTurnoServicioDelUsuario", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeTurnoServicioDelUsuarioResponse")]
        System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOTurnoServicio[]> LeeTurnoServicioDelUsuarioAsync(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeEmpleadoTurnoServicioCasino", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeEmpleadoTurnoServicioCasinoResponse")]
        EnroladorAccesoDatos.Dominio.POCOEmpleadoTurnoServicioCasino[] LeeEmpleadoTurnoServicioCasino(System.Guid GuidUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroladorServicioWeb/LeeEmpleadoTurnoServicioCasino", ReplyAction="http://tempuri.org/IEnroladorServicioWeb/LeeEmpleadoTurnoServicioCasinoResponse")]
        System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOEmpleadoTurnoServicioCasino[]> LeeEmpleadoTurnoServicioCasinoAsync(System.Guid GuidUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEnroladorServicioWebChannel : EnroladorStandAloneV2.EnroladorServicioWeb.IEnroladorServicioWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnroladorServicioWebClient : System.ServiceModel.ClientBase<EnroladorStandAloneV2.EnroladorServicioWeb.IEnroladorServicioWeb>, EnroladorStandAloneV2.EnroladorServicioWeb.IEnroladorServicioWeb {
        
        public EnroladorServicioWebClient() {
        }
        
        public EnroladorServicioWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnroladorServicioWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnroladorServicioWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnroladorServicioWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IdentificarHardware(System.Guid hardwareId) {
            return base.Channel.IdentificarHardware(hardwareId);
        }
        
        public System.Threading.Tasks.Task<bool> IdentificarHardwareAsync(System.Guid hardwareId) {
            return base.Channel.IdentificarHardwareAsync(hardwareId);
        }
        
        public EnroladorAccesoDatos.Dominio.POCOUsuario AutenticacionUsuario(string nombreUsuario, string claveUsuario) {
            return base.Channel.AutenticacionUsuario(nombreUsuario, claveUsuario);
        }
        
        public System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOUsuario> AutenticacionUsuarioAsync(string nombreUsuario, string claveUsuario) {
            return base.Channel.AutenticacionUsuarioAsync(nombreUsuario, claveUsuario);
        }
        
        public EnroladorAccesoDatos.Dominio.POCOUsuario Revalidar(EnroladorAccesoDatos.Dominio.POCOUsuario Usuario) {
            return base.Channel.Revalidar(Usuario);
        }
        
        public System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOUsuario> RevalidarAsync(EnroladorAccesoDatos.Dominio.POCOUsuario Usuario) {
            return base.Channel.RevalidarAsync(Usuario);
        }
        
        public EnroladorAccesoDatos.Dominio.POCOHuella[] LeeHuellasDelUsuario(System.Guid GuidUsuario) {
            return base.Channel.LeeHuellasDelUsuario(GuidUsuario);
        }
        
        public System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOHuella[]> LeeHuellasDelUsuarioAsync(System.Guid GuidUsuario) {
            return base.Channel.LeeHuellasDelUsuarioAsync(GuidUsuario);
        }
        
        public EnroladorAccesoDatos.Dominio.POCOCadena[] LeeCadenasDelUsuario(System.Guid GuidUsuario) {
            return base.Channel.LeeCadenasDelUsuario(GuidUsuario);
        }
        
        public System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOCadena[]> LeeCadenasDelUsuarioAsync(System.Guid GuidUsuario) {
            return base.Channel.LeeCadenasDelUsuarioAsync(GuidUsuario);
        }
        
        public EnroladorAccesoDatos.Dominio.POCOCargo[] LeeCargosDelUsuario(System.Guid GuidUsuario) {
            return base.Channel.LeeCargosDelUsuario(GuidUsuario);
        }
        
        public System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOCargo[]> LeeCargosDelUsuarioAsync(System.Guid GuidUsuario) {
            return base.Channel.LeeCargosDelUsuarioAsync(GuidUsuario);
        }
        
        public EnroladorAccesoDatos.Dominio.POCOContrato[] LeeContratosDelUsuario(System.Guid GuidUsuario) {
            return base.Channel.LeeContratosDelUsuario(GuidUsuario);
        }
        
        public System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOContrato[]> LeeContratosDelUsuarioAsync(System.Guid GuidUsuario) {
            return base.Channel.LeeContratosDelUsuarioAsync(GuidUsuario);
        }
        
        public EnroladorAccesoDatos.Dominio.POCOCuenta[] LeeCuentasDelUsuario(System.Guid GuidUsuario) {
            return base.Channel.LeeCuentasDelUsuario(GuidUsuario);
        }
        
        public System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOCuenta[]> LeeCuentasDelUsuarioAsync(System.Guid GuidUsuario) {
            return base.Channel.LeeCuentasDelUsuarioAsync(GuidUsuario);
        }
        
        public EnroladorAccesoDatos.Dominio.POCODispositivo[] LeeDispositivoDelUsuario(System.Guid GuidUsuario) {
            return base.Channel.LeeDispositivoDelUsuario(GuidUsuario);
        }
        
        public System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCODispositivo[]> LeeDispositivoDelUsuarioAsync(System.Guid GuidUsuario) {
            return base.Channel.LeeDispositivoDelUsuarioAsync(GuidUsuario);
        }
        
        public EnroladorAccesoDatos.Dominio.POCOEmpleadoDispositivo[] LeeEmpleadosDispositivos() {
            return base.Channel.LeeEmpleadosDispositivos();
        }
        
        public System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOEmpleadoDispositivo[]> LeeEmpleadosDispositivosAsync() {
            return base.Channel.LeeEmpleadosDispositivosAsync();
        }
        
        public EnroladorAccesoDatos.Dominio.POCOEmpresa[] LeeEmpresaDelUsuario(System.Guid GuidUsuario) {
            return base.Channel.LeeEmpresaDelUsuario(GuidUsuario);
        }
        
        public System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOEmpresa[]> LeeEmpresaDelUsuarioAsync(System.Guid GuidUsuario) {
            return base.Channel.LeeEmpresaDelUsuarioAsync(GuidUsuario);
        }
        
        public EnroladorAccesoDatos.Dominio.POCOHuella[] LeeTodasHuellas() {
            return base.Channel.LeeTodasHuellas();
        }
        
        public System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOHuella[]> LeeTodasHuellasAsync() {
            return base.Channel.LeeTodasHuellasAsync();
        }
        
        public EnroladorAccesoDatos.Dominio.POCOInstalacion[] LeeInstalacionesDelUsuario(System.Guid GuidUsuario) {
            return base.Channel.LeeInstalacionesDelUsuario(GuidUsuario);
        }
        
        public System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOInstalacion[]> LeeInstalacionesDelUsuarioAsync(System.Guid GuidUsuario) {
            return base.Channel.LeeInstalacionesDelUsuarioAsync(GuidUsuario);
        }
        
        public EnroladorAccesoDatos.Dominio.POCOEmpleado[] LeeTodosEmpleados() {
            return base.Channel.LeeTodosEmpleados();
        }
        
        public System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOEmpleado[]> LeeTodosEmpleadosAsync() {
            return base.Channel.LeeTodosEmpleadosAsync();
        }
        
        public EnroladorAccesoDatos.Dominio.POCOServicioCasino[] LeeServicioCasinoDelUsuario(System.Guid GuidUsuario) {
            return base.Channel.LeeServicioCasinoDelUsuario(GuidUsuario);
        }
        
        public System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOServicioCasino[]> LeeServicioCasinoDelUsuarioAsync(System.Guid GuidUsuario) {
            return base.Channel.LeeServicioCasinoDelUsuarioAsync(GuidUsuario);
        }
        
        public EnroladorAccesoDatos.Dominio.POCOTurnoServicio[] LeeTurnoServicioDelUsuario(System.Guid GuidUsuario) {
            return base.Channel.LeeTurnoServicioDelUsuario(GuidUsuario);
        }
        
        public System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOTurnoServicio[]> LeeTurnoServicioDelUsuarioAsync(System.Guid GuidUsuario) {
            return base.Channel.LeeTurnoServicioDelUsuarioAsync(GuidUsuario);
        }
        
        public EnroladorAccesoDatos.Dominio.POCOEmpleadoTurnoServicioCasino[] LeeEmpleadoTurnoServicioCasino(System.Guid GuidUsuario) {
            return base.Channel.LeeEmpleadoTurnoServicioCasino(GuidUsuario);
        }
        
        public System.Threading.Tasks.Task<EnroladorAccesoDatos.Dominio.POCOEmpleadoTurnoServicioCasino[]> LeeEmpleadoTurnoServicioCasinoAsync(System.Guid GuidUsuario) {
            return base.Channel.LeeEmpleadoTurnoServicioCasinoAsync(GuidUsuario);
        }
    }
}
